steps:
  - label: "Julia v1.7"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.7-nightly"
      - JuliaCI/julia-coverage#v1:
          codecov: true
    commands:
      - julia -e 'using Pkg; Pkg.add(name="Run", version="0.1")'
      - julia -e 'using Run; Run.prepare("test/environments/cuda-jl17")'
      - julia -e 'using Run; Run.test(project="test/environments/cuda-jl17")'
    agents:
      queue: "juliagpu"
      cuda: "*"
    if: |
      build.message !~ /^\[skip gpu\]/ &&
      build.message !~ /^\[skip cuda\]/
    timeout_in_minutes: 60

env:
  SECRET_CODECOV_TOKEN: "nzfKzFVQDgAG+f+/vft//CVb43EJ17gEleE0yQ/gXpl+vEAafEuMD3TrQ1vCtRZPKpr5mavHSUk9X9/nPnsoDmVvO7qbmyyee66i7FtaOdrCiihPLXe3gptt44uXx4E+3Q3bqZ748NneEt0pn+jWSigo4mJxewxETqddFLyPIpSKGTOnc6TWAX5b7qX1BXnlVggI4MqdZijFnJ6wu4jga8QKdvatf49SGQBINxz8OTkZpcRW+MlzJsG7gNZRm5eBp9J0alihe4a4wSGCStWzpbHMAV7nSI3ek7a8Y042h1JxCJ5hJ0llm6MW4y8MJz8DAVF35papCe6N7s6K21UFWQ==;U2FsdGVkX18p5ti+K5TGgvTqvdez3tsY57gWJjl1eiGXmNVEBvRaHSeEhtYi1HXJ0jc4JERzHZTAUgo4pnpqAA=="
